# Generated by Django 5.2 on 2025-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jikwon',
            fields=[
                ('jikwonno', models.IntegerField(primary_key=True, serialize=False)),
                ('jikwonname', models.CharField(max_length=10)),
                ('busernum', models.IntegerField()),
                ('jikwonjik', models.CharField(blank=True, max_length=10, null=True)),
                ('jikwonpay', models.IntegerField(blank=True, null=True)),
                ('jikwonibsail', models.DateField(blank=True, null=True)),
                ('jikwongen', models.CharField(blank=True, max_length=4, null=True)),
                ('jikwonrating', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'jikwon',
                'managed': False,
            },
        ),
    ]
